#ifndef MYPAGES_H
#define MYPAGES_H
#pragma once

const char* configIndex =
  "<form action='/config_post' method = 'post'>"
  "<label>hostname</label>"
  "<input type = 'text' name = 'hostname'/>"
  "<br/>"
  "<label>ssid</label>"
  "<input type = 'text' name = 'ssid'/>"
  "<br/>"
  "<label>password</label>"
  "<input type = 'text' name = 'password'/>"
  "<br/>"
  "<input type='submit' value='submit'>"
  "</form>"
  ;



const char* rootIndex =
  "<!DOCTYPE html>"
  "<html>"
  "<head>"
  "<meta name='viewport' content='width=device-width, initial-scale=1'>"
  "<script src='https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js'></script>"
  "<title>MK-312WS</title>"
  "<style>"
  "html{"
  "background-color: #ed008c;"
  "text-align: center;"
  "display: inline;"
  "max-width: 70%;"
  "margin: auto;"
  "}"
  ".body{"
  "font-size: 20px"
  "}"
  "button, input{"
  "font-size: 30px;"
  "background-color: #000080;"
  "border: none;"
  "color: white;"
  "margin: 2px;"
  "padding: 10px;"
  "}"
  "</style>"
  "</head>"
  "<body>"
  "<div class='body'>"
  // <h1><a href="/"><img src="/static/AlexaLogo.png" alt=""></a></h1>
  "<div id='mk312_sliders'>"
  "<div id='mk312_state'>loading...</div>"
  "<input type='range' min='0' max='99' value='0' class='slider' id='mk312_a' onmouseup=\"fetch('/MK312/A'+this.value)\">"
  "<input type='range' min='0' max='99' value='0' class='slider' id='mk312_b' onmouseup=\"fetch('/MK312/B'+this.value)\">"
  "<input type='range' min='0' max='99' value='0' class='slider' id='mk312_ma' onmouseup=\"fetch('/MK312/M'+this.value)\">"
  "</div>"
  "</div>"
  "</body>"
  "</html>"
  ;

const char* updateIndex =
  "<script src='https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js'></script>"
  "<form method='POST' action='#' enctype='multipart/form-data' id='upload_form'>"
  "<input type='file' name='update'>"
  "<input type='submit' value='Update'>"
  "</form>"
  "<div id='prg'>progress: 0%</div>"
  "<script>"
  "$('form').submit(function(e){"
  "e.preventDefault();"
  "var form = $('#upload_form')[0];"
  "var data = new FormData(form);"
  " $.ajax({"
  "url: '/update_post',"
  "type: 'POST',"
  "data: data,"
  "contentType: false,"
  "processData:false,"
  "xhr: function() {"
  "var xhr = new window.XMLHttpRequest();"
  "xhr.upload.addEventListener('progress', function(evt) {"
  "if (evt.lengthComputable) {"
  "var per = evt.loaded / evt.total;"
  "$('#prg').html('progress: ' + Math.round(per*100) + '%');"
  "}"
  "}, false);"
  "return xhr;"
  "},"
  "success:function(d, s) {"
  "console.log('success!')"
  "},"
  "error: function (a, b, c) {"
  "}"
  "});"
  "});"
  "</script>";
#endif //MYPAGES_H
